# Generated by Django 5.1.5 on 2025-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_event_comment_likes_discussion_is_expert_tip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='connect.product'),
        ),
    ]
