# Generated by Django 5.1.5 on 2025-05-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_alter_message_options_remove_message_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='operating_zone',
            field=models.CharField(blank=True, help_text='Primary operating zone/area', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Location or area of operation', max_length=255, null=True),
        ),
    ]
