# Generated by Django 5.1.5 on 2025-05-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_remove_comment_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_type',
            field=models.CharField(choices=[('self_pickup', 'Self Pickup'), ('boda_delivery', 'Boda Delivery')], default='self_pickup', max_length=20),
        ),
    ]
